version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7-jessie
    working_directory: /tmp/multipitch
    steps:
      - checkout
      - run:
          name: Build files
          command: |
            mkdir website
            cp index.html website
            cp -r about website
            cp -r cornakey-cliff website
            cp -r css website
            cp -r data website
            cp -r fonts website
            cp -r img website
            cp -r js website
            cp -r map website
            cp -r subscribe website

  deploy:
    docker:
      - image: circleci/python:2.7-jessie
    working_directory: /tmp/multipitch
    steps:
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Deploy to S3
          command: aws s3 sync website s3://com.multipitch/builds --delete

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
